name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: ps 0 test
      id: ps-0-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: ps 0 test
        setup-command: pip install pytest
        command: python test.py
        timeout: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PS-0-TEST_RESULTS: "${{steps.ps-0-test.outputs.result}}"
      with:
        runners: ps-0-test
